### ISSUE TITLE
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema. - options has an unknown property 'disableHostCheck'

### ISSUE THREAD

**Issue by AscaL** [single-spa/single-spa-vue#96]
Hi, 
I just created a vue-single-spa app. 
I have a root folder where I created a 'root-config' app (via CLI selecting the root-config option) and a 'vue' app (via CLI)
![image](https://user-images.githubusercontent.com/8880943/157451976-1ffbf4d9-b242-4085-9def-1f7577b9e69b.png)

After the setup, like suggested by the CLI, i ran npm run serve, which gave me this error:
```
INFO  Starting development server...
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'disableHostCheck'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'disableHostCheck'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (C:\Users\AscaL\Desktop\projects\single-spa-test\vue1\node_modules\webpack-dev-server\node_modules\schema-utils\dist\validate.js:115:11)     
    at new Server (C:\Users\AscaL\Desktop\projects\single-spa-test\vue1\node_modules\webpack-dev-server\lib\Server.js:232:5)
    at serve (C:\Users\AscaL\Desktop\projects\single-spa-test\vue1\node_modules\@vue\cli-service\lib\commands\serve.js:183:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I think it's related to Webpack. How can I fix it?

**Comment by lovelyGFR** [comment]
what's up？
